import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './comps/Navbar'
import Footer from './comps/Footer'

import { DataProvider } from "./context"
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <DataProvider>
      <body className={inter.className}><Navbar/>{children}</body>
      <Footer/>
      </DataProvider>
    </html>
  )
}
